import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";
import type { Viewport } from "next";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/Footer/Footer";

export const viewport: Viewport = {
  themeColor: "#e65100",
};

const mulish = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Best Mortgage Rates in Canada (Updated Daily)",
  description: "Generated by Joodi.me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${mulish.className} bgColor dark:bg-gray-700 overflow-y-auto`}
        >
          <ThemeProvider attribute="class" defaultTheme="light">
            <Navbar />
            {children}
            <Toaster />
            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
