import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import { ThemeProvider } from "@/Components/ThemeProvider";

const mulish = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Best Mortgage Rates in Canada (Updated Daily)",
  description: "Generated by Joodi.me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.className}`}>
      <ThemeProvider attribute="class" defaultTheme="light">
        <Navbar />
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
